test:
  adapter: postgresql
  encoding: unicode
  database: hero_api
  pool: 5
  username: hero_api
  password: peace2020

development:
  adapter: postgresql
  encoding: unicode
  database: hero_api
  pool: 5
  username: hero_api
  password: peace2020

production:
  adapter: postgresql
  encoding: unicode
  database: hero_api
  host: localhost
  pool: 5
  username: hero_api
  password: <%= ENV['DATABASE_PASSWORD'] %>